---
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/deployment-guides/ansible/
- hosts: all
  become: yes
  # Import tunnel variables into the VM.
  vars_files:
    - ./tf_ansible_vars_file.yml
  # Execute the following commands on the VM.
  tasks:
    - name: Download the cloudflared Linux package.
      shell: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    - name: Depackage cloudflared.
      shell: sudo dpkg -i cloudflared-linux-amd64.deb
    # When I try to install with package manager than  E:The repository 'http://pkg.cloudflare.com cloudflare-main Release' does not have a Release file.
    # https://pkg.cloudflare.com/index.html explain that we need to update url
    # so probably their repo is OS version specific so we do not use it
    # - name: Add Cloudflare GPG key
    #   apt_key:
    #     url: https://pkg.cloudflare.com/cloudflare-main.gpg
    #     state: present
    # - name: Add Cloudflare apt repository
    #   apt_repository:
    #     repo: "deb http://pkg.cloudflare.com/ cloudflare-main main"
    #     state: present
    # - name: Update apt cache
    #   apt:
    #     update_cache: yes
    # - name: Install cloudflared
    #   apt:
    #     name: cloudflared
    #     state: present
    # - name: Verify cloudflared installation
    #   command: cloudflared --version
    #   register: result
    #   changed_when: false
    # - name: Print cloudflared version
    #   debug:
    #     msg: "{{ result.stdout }}"

    # https://github.com/cloudflare/cloudflared/issues/1109
    # cat /var/log/cloudflared shows the error
    # {"level":"warn","error":"Group ID 0 is not between ping group 65534 to 65534","time":"2024-10-12T06:58:49Z","message":"The user running cloudflared process has a GID (group ID) that is not within ping_group_range. You might need to add that user to a group within that range, or instead update the range to encompass a group the user is already in by modifying /proc/sys/net/ipv4/ping_group_range. Otherwise cloudflared will not be able to ping this network"}
    # {"level":"warn","error":"cannot create ICMPv4 proxy: Group ID 0 is not between ping group 65534 to 65534 nor ICMPv6 proxy: socket: permission denied","time":"2024-10-12T06:58:49Z","message":"ICMP proxy feature is disabled"}
    - name: Set the ping_group_range
      sysctl:
        name: net.ipv4.ping_group_range
        value: "0 65534"
        state: present
        sysctl_set: yes  # Ensure it's set immediately
        reload: yes  # Reload sysctl configuration to apply changes
    - name: Persist the sysctl change
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ping_group_range'
        line: 'net.ipv4.ping_group_range = 0 65534'

    - name: Create a cloudflared service directory.
      shell: mkdir -p /etc/cloudflared/
    - name: Create the config file for cloudflared and define the ingress rules for the tunnel.
      copy:
        dest: "/etc/cloudflared/config.yml"
        content: |
          tunnel: "{{ tunnel_id }}"
          credentials-file: /etc/cloudflared/cert.json
          logfile: /var/log/cloudflared.log
          loglevel: info
          ingress:
            - hostname: "{{ hostname_22 }}"
              service: ssh://localhost:22
            - hostname: "{{ hostname_80 }}"
              service: http://localhost:80
            - service: http_status:404
    - name: Create the tunnel credentials file for cloudflared.
      copy:
        dest: "/etc/cloudflared/cert.json"
        content: |
          {
            "AccountTag"   : "{{ account | quote }}",
            "TunnelID"     : "{{ tunnel_id | quote }}",
            "TunnelName"   : "{{ tunnel_name | quote }}",
            "TunnelSecret" : "{{ secret | quote }}"
          }
    - name: Install the tunnel as a systemd service.
      shell: cloudflared service install
      ignore_errors: yes
    - name: Start the tunnel.
      systemd:
        name: cloudflared
        state: started
        enabled: true
        masked: no
